#!/usr/bin/env bash
# Generate the KAT-backed TBC oracle body (test-only) from the pinned
# tbc-calls file. The oracle lets SUBAGENT-M close gate M1 before the real
# primitive lands: known (Tweak, PT) pairs return the pinned CT, anything
# else returns zeros (loudly failing the KAT). Never edit the output by hand.
set -euo pipefail
SRC=../vectors/deoxysii256v141-tbc-calls.txt
OUT=deoxysii-tbc.adb
cd "$(dirname "$0")"

ada_bytes () { # "0a1b..." -> "16#0A#, 16#1B#, ..."
  local hex="$1" out="" i
  for ((i=0; i<${#hex}; i+=2)); do
    out+="16#${hex:i:2}#, "
  done
  printf '%s' "${out%, }"
}

{
  cat <<'HDR'
------------------------------------------------------------------------------
--  KAT-backed TBC oracle (TEST-ONLY; generated by gen-oracle.sh).
--  NOT the cipher. Shadows src/deoxysii-tbc.adb when tests are built with
--  -aItests/oracle ahead of -aIsrc, so the mode can be KAT-gated before the
--  real Deoxys-BC-384 lands (gate M1). Unknown inputs return zeros.
------------------------------------------------------------------------------

pragma SPARK_Mode (Off);

package body Deoxysii.TBC is

   type Call is record
      TW : Block_128;
      PT : Block_128;
      CT : Block_128;
   end record;

   type Call_Table is array (Positive range <>) of Call;

   Table : constant Call_Table := (
HDR

  n=0
  tw="" pt=""
  while IFS= read -r line; do
    case "$line" in
      "TWEAK = "*) tw="${line#TWEAK = }" ;;
      "PT = "*)    pt="${line#PT = }" ;;
      "CT = "*)
        ct="${line#CT = }"
        n=$((n+1))
        [ "$n" -gt 1 ] && printf ',\n'
        printf '      %d => (TW => (%s),\n            PT => (%s),\n            CT => (%s))' \
          "$n" "$(ada_bytes "$tw")" "$(ada_bytes "$pt")" "$(ada_bytes "$ct")"
        ;;
    esac
  done < "$SRC"

  cat <<'FTR'
);

   function TBC_Encrypt_384 (Key       : Key_256;
                             Tweak     : Block_128;
                             Plaintext : Block_128)
                             return Block_128
   is
      pragma Unreferenced (Key);
   begin
      for E of Table loop
         if E.TW = Tweak and then E.PT = Plaintext then
            return E.CT;
         end if;
      end loop;
      return (others => 0);   --  unknown input: fail the KAT loudly
   end TBC_Encrypt_384;

end Deoxysii.TBC;
FTR
} > "$OUT"
echo "oracle entries: $n -> $OUT"
